### PR TITLE
Return probabilities from CausalTransformer.generate()

### LINKED ISSUE #41: Return probabilities from CausalTransformer.generate()
The GPT-3 API allows you to fetch probabilities when you generate text. This is helpful for debugging or when using the probabilities to do few-shot classification. It would be great if this feature was also available for GPT-J.

For each generated token there would also be a full list of probabilities for each item in the vocabulary. Then you could look up the probability at any step given a token.

gpt-3_probabilities_1500x1124

### PR DESCRIPTION
**Pull request by narphorium**
Convert logits to probabilities for all classes at every generation step and return them as single tensor with shape (1, gen_length, 1, vocab) in the output of CausalTransformer.generate()

resolves #41

### CODE REVIEW

**Review by kingoflolz — CHANGES_REQUESTED** [review]
Thanks! A couple suggestions:

- Return logits instead of probability as you retain more information that way (easy to go one way, harder to go the other)
- Make this logit output optional (defaulting to not output) as otherwise this would be a nontrivial memory penalty for applications that do not require this (and also break some existing code haha)

**Comment by narphorium** [comment]
Sounds good. I've switched it back to logits and made them optional with a named parameter on generate()

**Comment by kingoflolz** [comment]
Thanks for the changes! Did you manage to test this? I'm not sure if the generate_xmap will be happy with the optional argument.

**Comment by narphorium** [comment]
Ah, you're right. xmap() didn't like the named parameter so I switched it to an attribute like gen_length. Tested it in the colab notebook and it works.

**Comment by kingoflolz** [comment]
Thanks!

**Comment by leonhuene** [comment]
@narphorium Thanks so much for doing this! Is there a usage example on how to extract the probabilities?

**Comment by narphorium** [comment]
@leonhuene glad you find it useful. Here's some more info on how to extract the logits and turn them into probabilities.

In the [Colab demo](https://github.com/kingoflolz/mesh-transformer-jax/blob/master/colab_demo.ipynb) there's an `infer()` function  which makes a call to `CausalTransformer.generate()` which my PR has modified. You'll need to add the `return_logits` parameter to access the new feature like this:

```
output = network.generate(
        batched_tokens, 
        length, 
        gen_len, 
        {
          "top_p": np.ones(total_batch) * top_p, 
          "temp": np.ones(total_batch) * temp
         }, 
        return_logits=True)
```

The `output` of that call returns a tuple of `(last_state, predictions)` and both the predicted tokens and their logits are contained in the second part of that tuple. The predictions are another tuple of `(decoded_tokens, None, all_logits)`. `decoded_tokens` is a tensor with shape `(1, gen_len, 1)` and `all_logits` is a tensor with shape `(1, gen_len, 1, vocab) `. This means that, for every generation step, you can get the predicted token and its logits like this:

```
decoded_tokens = output[1][0]
all_logits = output[1][2]
step = 0
token = decoded_tokens[0][step]
logits = all_logits[0][step]
```

Then to turn the token ID into text and the logits into a probability you can do:

```
text = tokenizer.decode(decoded_token)
probability = jax.nn.softmax(logits[0])[token[0]]
```

If you want to calculate the combined probability for all the decoded tokens, you can do it like this:

```
text = ''
probability = 1.0
for token, logits in zip(decoded_tokens[0], all_logits[0]):
  text += tokenizer.decode(token)
  probability *= jax.nn.softmax(logits[0])[token[0]]
```

If you want to see what the probability of a different set of tokens would be, you can feed that in like this:

```
alternate_text = ' singing alone'
alternate_tokens = tokenizer.encode(alternate_text)
probability = 1.0
for token, logits in zip(alternate_tokens, all_logits[0]):
  probability *= jax.nn.softmax(logits[0])[token]
```

**Comment by leonhuene** [comment]
@narphorium I couldn't have asked for a more comprehensive, helpful, clear, and beginner-friendly response. I cannot thank you enough! I cannot wait to try this.

**Comment by kingoflolz** [comment]
@narphorium Looks like you have a stray return_logits=return_logits in the generate_xmap call which breaks it. Do you mind recreating the PR?

**Comment by leonhuene** [comment]
I was just about to comment when just testing the regular Colab I did get this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-91521d69bfdb> in <module>()
     21     return samples
     22 
---> 23 print(infer('''EleutherAI is''')[0])

1 frames
<ipython-input-9-91521d69bfdb> in infer(context, top_p, temp, gen_len)
     10 
     11     start = time.time()
---> 12     output = network.generate(batched_tokens, length, gen_len, {"top_p": np.ones(total_batch) * top_p, "temp": np.ones(total_batch) * temp}, return_logits=False)
     13 
     14     samples = []

/usr/local/lib/python3.7/dist-packages/mesh_transformer/transformer_shard.py in generate(self, ctx, ctx_length, gen_length, sampler_options, return_logits)
    331                                   aux,
    332                                   sampler_options,
--> 333                                   return_logits=return_logits)
    334 
    335 

TypeError: fun_mapped() got an unexpected keyword argument 'return_logits'
```

**Comment by narphorium** [comment]
Yikes, sorry about that. I've fixed it in #63

**Comment by 6r1d** [comment]
Hello.

I was wondering how different logits here behave compared to OpenAI logprobs in [completions](https://beta.openai.com/docs/api-reference/completions).
If I understand it correctly, logprob is the [log of the probability of the token to appear next](http://gptprompts.wikidot.com/intro:logprobs), and logit is log(probability/1-probability) for the next token.
Does it change how I should interpret the probabilities of GPT-j a lot?

@kingoflolz, you've mentioned "you retain more information" with logits; are there some additional uses for logits compared to logprobs?

@narphorium, `logits[0]` in `all_logits[0]` seem to be a vector (I conclude that by the `[token]` indexing).
Is this part related to only this token?

> If you want to see what the probability of a different string of tokens would be, you can feed that in like this:

Would that be a comparison with a single generated result, or a "possible range" of all the completions?

(After Gwern's comment I started to wonder about OpenAI-like semantic search and I wonder if it's possible to implement something similar with this "probability for a string of tokens" approach.)

https://cdn.discordapp.com/attachments/729741769738158194/854413286996967424/Screenshot_20210615-193256.png

**Comment by narphorium** [comment]
@6r1d `all_logits` has shape `(1, gen_len, 1, vocab)` so `all_logits[0]` is just removing the first dimension (batch of size 1).

In the example code that I gave, I then iterate through `all_logits[0]` which gives us each element from the 2nd dimension of `(1, gen_len, 1, vocab)`. `gen_len` is the number of tokens which were generated. This is makes `logits` a vector of shape `(1, vocab)` as we loop through each decoded token. We then remove the extra dimension again by getting `logits[0]` so that we are left with a vector of size `(vocab)` from which we can plug-in a token ID and get the specific prediction for that token at that decoding step and turn it into a probability using the formula that you gave.

If you turn the GPT-3 logprobs back into probabilities (`np.e**logprobs`) then you will have probabilities like the ones that I've described here. Of course, they're two different models trained on different datasets so don't expect the actual probabilities themselves to be the same.

If you want, you can run generate multiple times to get a range of different completions and then use the techniques described here to compare the probabilities of each completion.

**Pull request merged**
