### PR TITLE
Significantly reduce vram usage when resharding on a single GPU.

### PR DESCRIPTION
**Pull request by AeroScripts**
Without this, the model is actually duplicated in memory due to xmap.

I am testing with a single RTX 3090 on Ubuntu 20.04.2 LTS.
jax versions:
```
jax==0.2.13
jaxlib==0.1.67+cuda111
```

I also run with the following environment variables, otherwise it OOMs during init regardless of this change:
```
XLA_PYTHON_CLIENT_PREALLOCATE=false
XLA_PYTHON_CLIENT_ALLOCATOR=platform
```

Some stats on running infer() with and without this change:

before:
```
seq     vram usage
512     21.1G
900     22.3G
```

after:
```
seq     vram usage
512     14.7G
900     15.3G
2048    22.4G
```

It still uses a bit more than that during initialization though.

### CODE REVIEW

**Review by kingoflolz — COMMENTED** [review]
Looks good, could you also update the comment at the top of the doc with what you are testing with? (and maybe what JAX flags you needed to use to get there?)

**Comment by AeroScripts** [comment]
Sure thing, updated 👍

**Comment by kingoflolz** [comment]
Oops don't think I was clear, I meant updating the comment at line 1 of resharding_example.py with the info from your PR

**Comment by AeroScripts** [comment]
Updated the comment 👍 

Also added the default configuration (seq=2048) to the table above

**Comment by kingoflolz** [comment]
Looks good, is there anything else you want to play with or is this good to merge?

**Comment by AeroScripts** [comment]
Good to merge I think, next thing I'm going to do is try implementing more sampling options, if you are open to PRs for that

**Comment by kingoflolz** [comment]
Sounds great, happy to talk through things on discord as well

**Pull request merged**
